apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: toxpcde8f-dotnet-basic-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/toxpcde8f-dotnet-basic