apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: toxpcde8f-dotnet-basic-gitops
  description: This is GitOps manifest for toxpcde8f-dotnet-basic   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=toxpcde8f-dotnet-basic
    backstage.io/kubernetes-id: toxpcde8f-dotnet-basic 
    backstage.io/techdocs-ref: dir:. 
    jenkins.io/job-full-name: toxpcde8f-dotnet-basic-gitops
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:toxpcde8f-dotnet-basic
